//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGPI
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities1 : DbContext
    {
        public Entities1()
            : base("name=Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Asignatura> Asignatura { get; set; }
        public virtual DbSet<Documento> Documento { get; set; }
        public virtual DbSet<Entrevista> Entrevista { get; set; }
        public virtual DbSet<Estudiante> Estudiante { get; set; }
        public virtual DbSet<Genero> Genero { get; set; }
        public virtual DbSet<Homologacion> Homologacion { get; set; }
        public virtual DbSet<Pagos> Pagos { get; set; }
        public virtual DbSet<Programa> Programa { get; set; }
        public virtual DbSet<Programacion> Programacion { get; set; }
        public virtual DbSet<Rol> Rol { get; set; }
        public virtual DbSet<TipoHomologacion> TipoHomologacion { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    }
}
