//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Homologacion
    {
        public int IdHomologacion { get; set; }
        public int IdEstudiante { get; set; }
        public string PeriodoAcademico { get; set; }
        public int IdPrograma { get; set; }
        public int IdTipoHomologacion { get; set; }
        public int IdAsignatura { get; set; }
        public string CodigoHomologacion { get; set; }
        public string NombreAsignaturaHomologar { get; set; }
        public int Creditos { get; set; }
        public double NotaDefinitiva { get; set; }
    
        public virtual Asignatura Asignatura { get; set; }
        public virtual Estudiante Estudiante { get; set; }
        public virtual Programa Programa { get; set; }
        public virtual TipoHomologacion TipoHomologacion { get; set; }
    }
}
