//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Programacion
    {
        public int IdProgramacion { get; set; }
        public string PeriodoAcademico { get; set; }
        public Nullable<int> IdPrograma { get; set; }
        public Nullable<System.DateTime> FechaPrograma { get; set; }
        public string Sala { get; set; }
        public Nullable<int> IdAsignatura { get; set; }
        public Nullable<int> IdUsuario { get; set; }
    
        public virtual Asignatura Asignatura { get; set; }
        public virtual Programa Programa { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
