//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuario()
        {
            this.Entrevista = new HashSet<Entrevista>();
            this.Programacion = new HashSet<Programacion>();
        }
    
        public int IdUsuario { get; set; }
        public string Documento { get; set; }
        public int IdDocumento { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public int IdGenero { get; set; }
        public string Email { get; set; }
        public int IdRol { get; set; }
        public string Contraseña { get; set; }
        public int IdPrograma { get; set; }
    
        public virtual Documento Documento1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Entrevista> Entrevista { get; set; }
        public virtual Genero Genero { get; set; }
        public virtual Programa Programa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Programacion> Programacion { get; set; }
        public virtual Rol Rol { get; set; }
    }
}
